### ISSUE TITLE
Feature request: allow reading `mongo` config from file

### ISSUE THREAD

**Issue by menzenski** [z3z1ma/tap-mongodb#3]
I'd like to use this tap with some MongoDB clusters that use hashicorp vault to manage credentials. If I could read the `mongo` config setting from a file (JSON, YAML, even just a plain text file with a MongDB URI connection string) then I'd be able to easily use this tap in that scenario.

**Comment by z3z1ma** [comment]
Thanks for contribution + issue sir!
